[package]
name = "aoc"
version = "0.1.0"
authors = ["Kristin Davidson <k@kxd.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5"
regex = "1.4.2"